-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 16:03:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE USER IF NOT EXISTS 'adlister_user'@'localhost' IDENTIFIED BY 'fresh_Headshot-2020';
GRANT ALL ON adlister_database.* TO 'adlister_user'@'localhost';
-- -----------------------------------------------------
-- Schema adlister_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adlister_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adlister_database` DEFAULT CHARACTER SET utf8 ;
USE `adlister_database` ;

-- -----------------------------------------------------
-- Table `adlister_database`.`ads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_database`.`ads` ;

CREATE TABLE IF NOT EXISTS `adlister_database`.`ads` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(240) NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `date_posted` DATE NOT NULL,
  `image_blob` BLOB NULL,
  `image_text` LONGTEXT NULL,
  `review_avr` TINYINT(6) UNSIGNED NULL,
  `category_id` VARCHAR(50) NOT NULL,
  `quantity_reported` INT UNSIGNED NOT NULL,
  `users_reported` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adlister_database`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_database`.`users` ;

CREATE TABLE IF NOT EXISTS `adlister_database`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `image` BLOB NULL,
  `image_text` LONGTEXT NULL,
  `user_avr` TINYINT(6) UNSIGNED NOT NULL,
  `users_followed` LONGTEXT NULL,
  `times_reported` INT UNSIGNED NOT NULL,
  `num_ads_reported` INT UNSIGNED NOT NULL,
  `num_reviews` INT UNSIGNED NOT NULL,
  `wishlist` LONGTEXT NULL,
  `zipcode` INT UNSIGNED NOT NULL,
  `isAdmin` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_users_ads1`
    FOREIGN KEY (`id`)
    REFERENCES `adlister_database`.`ads` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adlister_database`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_database`.`reviews` ;

CREATE TABLE IF NOT EXISTS `adlister_database`.`reviews` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `review_text` VARCHAR(250) NOT NULL,
  `rating` TINYINT(6) UNSIGNED NOT NULL,
  `image` BLOB NULL,
  `image_text` LONGTEXT NULL,
  `ad_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_reviews_ads1_idx` (`ad_id` ASC),
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `adlister_database`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_ads1`
    FOREIGN KEY (`ad_id`)
    REFERENCES `adlister_database`.`ads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
